plugins {
	id 'fabric-api.module'
}

loom {
	accessWidenerPath = file("src/main/resources/fabric-biome-api-v1.classtweaker")
}

fabricApiModule {
	testDependencies(
		':fabric-api-base',
		':fabric-resource-loader-v1',
		':fabric-registry-sync-v0',
		':fabric-data-generation-api-v1'
	)
}

fabricApi {
	configureDataGeneration {
		outputDirectory = file("src/testmod/generated")
		addToResources = false
		strictValidation = true
	}
}

runDatagen {
	outputs.dir("src/testmod/generated")
}

sourceSets {
	testmod {
		resources {
			srcDirs += [
				'src/testmod/generated'
			]
		}
	}
}

loom {
	runs {
		datagen {
			displayName = "Data Generation"
			sourceSet = sourceSets.testmod.name
			generateRunConfig = true
		}
	}
}

generateResources.dependsOn runDatagen
