files:
  - source: /*/src/*/resources/assets/*/lang/en_us.json
    translation: "%original_path%/%original_file_name%"
    translation_replace:
      en_us: "%locale_with_underscore%"
    ignore: [/*/src/test*]
preserve_hierarchy: true
project_id: "647524"
