plugins {
	id 'groovy-gradle-plugin'
	id 'checkstyle'
	alias(libs.plugins.spotless)
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	gradlePluginPortal()
	mavenCentral()
}

dependencies {
	implementation libs.fabric.loom
	implementation "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:${libs.versions.spotless.get()}"
	implementation "me.modmuss50.remotesign:me.modmuss50.remotesign.gradle.plugin:${libs.versions.remote.sign.get()}"
	implementation "me.modmuss50.mod-publish-plugin:me.modmuss50.mod-publish-plugin.gradle.plugin:${libs.versions.mod.publish.get()}"
}

checkstyle {
	configFile = file("../checkstyle.xml")
	toolVersion = libs.versions.checkstyle.get()
}

spotless {
	lineEndings = com.diffplug.spotless.LineEnding.UNIX

	java {
		target("src/main/java/**/*.java")
		licenseHeaderFile(file("../HEADER"))
		removeUnusedImports()
		importOrder('java', 'javax', '', 'net.minecraft', 'net.fabricmc')
		leadingSpacesToTabs()
		trimTrailingWhitespace()
	}
}

tasks.withType(Checkstyle).configureEach {
	source = fileTree("src/main/java")
}
