import net.fabricmc.fabric.impl.build.FabricApiBuildUtils
import org.gradle.api.publish.maven.MavenPublication

plugins {
	id "fabric-api.base-publishing"
}

base {
	archivesName = project.name
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			pom {
				FabricApiBuildUtils.addPomMetadataInformation(project, pom)
			}
			artifact(tasks.jar.archiveFile) {
				builtBy(tasks.jar)
			}
			artifact(tasks.sourcesJar) {
				builtBy tasks.sourcesJar
			}
		}
	}
}

remoteSign {
	sign publishing.publications.mavenJava
	sign jar
}

String archivesName = project.base.archivesName.get()
[jar, sourcesJar].each {
	it.from(rootProject.file("LICENSE")) {
		rename { "${it}-${archivesName}" }
	}
}

tasks.withType(PublishToMavenRepository).configureEach {
	onlyIf {
		def projectName = project.name
		def projectVersion = project.version.toString()
		def exists = FabricApiBuildUtils.publishedArtifactExists(project, projectName, projectVersion)

		if (exists) {
			logger.lifecycle("${projectName}-${projectVersion}.pom has already been published")
		} else if (providers.environmentVariable("MAVEN_URL").present) {
			logger.lifecycle("${projectName}-${projectVersion}.pom does not exist, publishing")
		}

		return !exists
	}
}

loom.disableDeprecatedPomGeneration(publishing.publications.mavenJava)
javadoc.enabled = false
