import net.fabricmc.fabric.impl.build.FabricApiModuleExtension

plugins {
	id "fabric-api.module-versioning"
	id "fabric-api.java"
	id "fabric-api.lint"
	id "fabric-api.loom"
	id "fabric-api.testing"
	id "fabric-api.module-outputs"
	id "fabric-api.validation"
	id "fabric-api.publishing"
}

extensions.create("fabricApiModule", FabricApiModuleExtension, project)
