import net.fabricmc.loom.task.tool.ModEnigmaTask
import net.fabricmc.fabric.impl.build.FabricApiBuildUtils

plugins {
	id "net.fabricmc.fabric-loom"
}

loom {
	splitEnvironmentSourceSets()
	runtimeOnlyLog4j = true
	runs.configureEach {
		preferGradleTask = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
	api FabricApiBuildUtils.library(project, "fabric-loader")
}

tasks.withType(ProcessResources).configureEach {
	def modVersion = project.version.toString()
	inputs.property "version", modVersion

	filesMatching("fabric.mod.json") {
		expand "version": modVersion
	}
}

tasks.register('generateResources') {
	group = "fabric"
}

tasks.register('enigma', ModEnigmaTask) {
	def clientOnly = file('src/client').exists() && !file('src/main').exists()
	def dir = clientOnly ? file('src/client/resources') : file('src/main/resources')
	mappingFile = new File(dir, project.name + '.mapping')
}
