import net.fabricmc.fabric.impl.build.FabricApiBuildUtils
import org.gradle.api.publish.maven.MavenPublication

plugins {
	id "fabric-api.base-publishing"
}

version = rootProject.version

def dependencies = rootProject.allprojects.findAll {
	it.name != "deprecated" && it.path.startsWith(":deprecated")
}.collect {
	[
		'groupId': project.group.toString(),
		'artifactId': it.name,
		'version': FabricApiBuildUtils.moduleVersion(it),
		'scope': 'compile'
	]
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = 'fabric-api-deprecated'

			pom.withXml {
				def depsNode = asNode().appendNode("dependencies")
				for (dep in dependencies) {
					def depNode = depsNode.appendNode("dependency")
					depNode.appendNode("groupId", dep['groupId'])
					depNode.appendNode("artifactId", dep['artifactId'])
					depNode.appendNode("version", dep['version'])
					depNode.appendNode("scope", dep['scope'])
				}
			}
		}
	}
}

remoteSign {
	sign publishing.publications.mavenJava
}
