import net.fabricmc.fabric.impl.build.FabricApiBuildUtils

plugins {
	id "fabric-api.module"
}

sourceSets {
	mixinConfig {
		compileClasspath += configurations.loaderLibraries
	}
	client {
		compileClasspath += mixinConfig.output
		runtimeClasspath += mixinConfig.output
	}
}

configurations {
	clientImplementation.extendsFrom mixinConfigImplementation
	clientRuntimeOnly.extendsFrom mixinConfigRuntimeOnly
}

dependencies {
	mixinConfigImplementation FabricApiBuildUtils.library(project, "fabric-loader")
}

tasks.named("jar", Jar) {
	from sourceSets.mixinConfig.output
}
